### ISSUE TITLE
Vercel deployment for examples

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#102]
# Why

In #83 we created new examples that make use of our published packages. Now we want to deploy these examples automatically to Vercel.

# TODOS

- [x] Create two new Vercel applications, after this change we should have: react-playground, react-sdk-playground, react-example, react-sdk-example
- [x] Make sure that example applications are deployed automatically when there is a push on master
- [x] Rename playground/react-example => playground/react and playground/react-sdk-example => playground/react-sdk

# Acceptance criteria

- [x] GitHub actions are both green
- [x] Playground and example applications work
