### ISSUE TITLE
Add tests on Playwright

### ISSUE THREAD

**Issue by aehnh** [corbado/javascript#111]
# Why

End-to-end tests should be implemented for every possible scenario on every page so that implementations on different frontend frameworks can be automatically tested with Github Actions upon merging to main.

# TODOS

Login flow
- InitiateLogin page
    - [x] [+] "Create account" button redirects to InitiateSignup page
    - [x] [+] "Continue with email" with registered email prompts passkey input if passkeys available and registered from current device
    - [x] [+] "Continue with email" with registered email redirects to EmailOTP page if passkey not registered from current device
    - [x] [+] Conditional UI prompts passkey input without redirecting
    - [x] [+] Correct passkey input redirects to LoggedIn page
    - [x] [-] "Continue with email" with unregistered/invalid email displays error
- PasskeyBenefits page
    - [x] [+] "Create passkey" button prompts passkey input [duplicate]
    - [x] [-] "Maybe later" button redirects to LoggedIn page
- PasskeyAppend page
    - [x] [+] "Activate" button prompts passkey input [duplicate]
    - [x] [+] Correct passkey input redirects to LoggedIn page [duplicate]
    - [x] [-] "Passkeys" button redirects to PasskeyBenefits page no matter what [duplicate]
    - [x] [-] Cancelling passkey redirects to LoggedIn page [duplicate]
    - [x] [-] "Maybe later" button redirects to LoggedIn page [duplicate]
- EmailOTP page
    - [x] [+] Inputing correct OTP code immediately redirects to LoggedIn page if device doesn't support passkeys [duplicate]
    - [x] [+] Inputing correct OTP code immediately redirects to PasskeyAppend page if device supports passkeys [duplicate]
    - [x] [-] "Cancel" button redirects to InitiateLogin page
    - [x] [-] "Continue" button with incomplete OTP code displays "The provided OTP is not valid", does not redirect [duplicate]
    - [x] [-] "Continue" button with wrong OTP code displays "The provided OTP is not valid", does not redirect [duplicate]
    - [x] [-] Inputing wrong OTP code displays "The provided OTP is not valid", does not redirect [duplicate]
    - [x] [-] "Google", "Yahoo", "Outlook" buttons redirect to appropriate links [duplicate]

Signup flow
- InitiateSignup page
    - [x] [+] "Login" button redirects to InitiateLogin page
    - [x] [+] "Continue with email" with correct inputs redirects to PasskeySignup page or EmailOTP page depending on passkey availability
    - [x] [-] Name violations (special characters, length limit, etc.)
    - [x] [-] Email address violations (duplicate emails, invalid emails)
- PasskeySignup page
    - [x] [+] "Passkeys" button redirects to PasskeyBenefits page
    - [x] [+] "Create account" button prompts passkey input
    - [x] [+] Successful passkey input redirects to PasskeyWelcome page
    - [x] [-] Cancelling passkey input stays on same page (not implemented yet)
    - [x] [-] "Send email one time code" button redirects to EmailOTP page
    - [x] [-] "back" button redirects to InitiateSignup page
    - [x] [-] "Passkey" link redirects to PasskeyBenefits page
- PasskeyBenefits page
    - [x] [+] "Create passkey" button prompts passkey input
    - [x] [+] Successful passkey input redirects to PasskeyWelcome page
    - [x] [-] "Maybe later" button redirects to EmailOTP page
- PasskeyAppend page
    - [x] [+] "Activate" button prompts passkey input
    - [x] [+] Successful passkey input redirects to PasskeyWelcome page
    - [x] [-] "Passkeys" button redirects to PasskeyBenefits page no matter what
    - [x] [-] Cancelling passkey redirects to LoggedIn page
    - [x] [-] "Maybe later" button redirects to LoggedIn page
- EmailOTP page
    - [x] [+] Inputing correct OTP code immediately redirects to LoggedIn page if device doesn't support passkeys
    - [x] [+] Inputing correct OTP code immediately redirects to PasskeyAppend page if device supports passkeys
    - [x] [-] "Cancel" button redirects to InitiateSignup page
    - [x] [-] "Continue" button with incomplete OTP code displays "The provided OTP is not valid", does not redirect
    - [x] [-] "Continue" button with wrong OTP code displays "The provided OTP is not valid", does not redirect
    - [x] [-] Inputing wrong OTP code displays "The provided OTP is not valid", does not redirect
    - [x] [-] "Google", "Yahoo", "Outlook" buttons redirect to appropriate links
- PasskeyWelcome page
    - [x] [+] "Continue" button redirects to LoggedIn page

LoggedIn page
- [ ] [+] "Create a passkey" button prompts passkey input
- [ ] [+] Correct passkey input displays new passkey information in the list
- [ ] [+] Clicking trashcan icon on a generated passkey deletes it from the list

Additional tests
- [ ] check if "back" gesture (e.g. third mouse button, or 2-finger swipe on touchpad) from any of the above stages has intended effect
- [x] check if passkey was successfully created in LoggedIn page (especially if registered from PasskeyAppend)

**Comment by aehnh** [comment]
The rest of the tests do not test the complexities involved in the flow so they are not very important
