### ISSUE TITLE
Publish web-js and add it to examples

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#116]
# Why

We still need to publish web-js. As it should be usable via npm and via script tag we need to publish it to npmjs and we need to offer the bundle for download. Finally, we want to prove that both of these published versions work by including them in an example.

# TODOS

- [ ] Decide for a way to host the bundle (maybe just a GH release for now?)
- [ ] Include web-js in release:publish
- [ ] Add two brief examples, they can be very simple and they should be as similar as possible => maybe we just differentiate them by adding a different headline, like "Corbado web-js (npm)" and "Corabdo web-js (script)".

# Acceptance criteria

- [ ] Examples using the published versions run locally and on Vercel (I can add the config for the Vercel  deployment)

# Implementation idea

- GitHub to host the bundle releases? (or is there an easier way)
- Use pro-1743528526530787479 as a projectID for local and pro-3652881945085154854 as a projectID for Vercel (they both have been configured with the right relying party IDs)
