### ISSUE TITLE
Several UI Fixes

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#121]
# Why

Vincent and I went through the components again. In this ticket we list the things that we want to fix before releasing the component.

# TODOS

- [x] Make email address bold in emailOTP screens
- [x] SVGs are loading to slow (compared to the legacy component)
- [x] Buttons should have more vertical padding (height should be equal to the inputs)
- [x] Inputs should not flicker when they are focused
- [x] Replace red/blue in passkey delete dialog with primary/secondary

# Bugs on Windows Edge/Firefox

- [ ] Firefox, when navigating to login
![image](https://github.com/corbado/javascript/assets/134682658/abf48934-7134-462d-b29c-2a0806853410)

- [ ] Edge auto-complete uses TimesNewRoman as font-family
- [ ] Email OTPs can not successfully be submitted in Edge
