### ISSUE TITLE
Add Support for new SignUp Flow

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#127]
# Why

Right now, we only support a single flow in our component (PasskeySignupWithEmailOTPFallback). We now add support for a second one (EmailOTPSignupWithPasskeyAppend). Additionally, we want to change the structure of our translations and do a few re-namings to increase the consistency in our codebase.

# TODOS
- [ ] Adjust flowmanager to support the new flow
- [ ] Add an additional layer to our translations file and to the screens directory in our codebase
- [ ] We now need to duplicate files in our screens folder => check if we can decrease the amount of duplicated code
- [ ] Renamings: InitiateSignup.tsx => Start.tsx (we need the same change in login), PasskeyWelcome.tsx => PasskeySuccess.tsx, PasskeySignup.tsx => PasskeyCreate.tsx

# Acceptance criteria
- [ ] New flow works in playground and in examplesy
- [ ] Separate translations are supported for the two flows
- [ ] Files in screens folder are consistently named and are in sync with constant.ts

# Implementation idea
- take a look at the figma (the new signUp flow is above the old one, headline is "Signup with OTP (mandatory)")
