### ISSUE TITLE
Export CorbadoSignUp and CorbadoLogin as components

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#130]
# Why

Currently we export CorbadoAuth as a component that bundles the SignUp and Login component. As some users might want to show these components on different routes inside their application we want to enable them to do so by exporting these two components also individually.

# TODOS
- [ ] Refactor AuthFlow to support both use cases (CorbadoAuth and CobadoSignUp/CorbadoLogin)
- [ ] Demonstrate that the new components are working by including them inside the react example (it could just show both approaches)
- [ ] Allow the user to configure a callback for CobadoSignUp/CorbadoLogin and rename the existing callback (onLoggedIn)

# Acceptance criteria
- [ ] All components should still work
- [ ] React playground demonstrates the usage of these new components but also the usage of CorbadoAuth

# Implementation idea
