### ISSUE TITLE
Add support for email magic link

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#131]
# Why

Currently our component support email OTP (e.g. for fallback login/signups). Some of our users that right now use the legacy component make use of a feature called magic links that is part of the legacy component. In our new component we want to support both options (otp and magiclinks). 

We already have Figma designs for magic links (they are right below the OTP ones).

# TODOS
- [ ] Implement magic links as an alternative to email otp (users should be able to configure this from their backend)

# Acceptance criteria
- [ ] email OTP should still work
- [ ] it should be possible to switch from OTP to magic links and vice versa

# Implementation idea

As magic links are already implemented in the legacy component, take a look at both the Figma and the old component (you can see it live in action also when going to app.corbado.com because we still use that component there).
