### ISSUE TITLE
Follow up email links

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#142]
# Why
As we now also added email links as a second verification method, we want to improve two things for this flow:
- make it easier to test in our playground
- improve the EmailLinkComplete screen

# TODOS
- [ ] Add a loading animation during the verification on EmailLinkComplete
- [ ] Implement the email resend (add a 30s timer that prevents spamming, similar as in the legacy webcomponent)
- [ ] Add another testing button to the react playground so that we can test emailLinks (for implementation idea, see details below)

# Implementation idea
To make testing easier we could add another button to the root route of main.react.playground.corbado.io.
On this page I would now show two buttons:
- CorbadoAuth Email OTP => routes to /pro-3652881945085154854/auth (show <CorbadoAuth/> wrapped with a <CorbadoProvider/> with pro-3652881945085154854)
- CorbadoAuth Email Link => routes to /pro-8125835201872404154/auth (show <CorbadoAuth/> wrapped with a <CorbadoProvider/> with pro-8125835201872404154)
=> so we would need to move the CorbadoProvider down in the component hierarchy so that is gets access to the path variable

<SignUp/> and <Login/> should then be available under /pro-XXX/signup and /pro-XXX/login. We can allow the username to navigate there by adding two buttons below the CorbadoAuth component under /pro-XXX/auth
