### ISSUE TITLE
Respect projectSessions: allowUserRegistration + userFullNameRequired

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#168]
# Why

The legacy web component supported two settings that we have not supported yet in the new components. The projectConfig call already returns their values and both values can be changed in the developer panel. We now want to respect them in our new components also.

For context, this is the place in our dev panel where we edit these settings:
![Screenshot 2024-01-30 at 11 21 54](https://github.com/corbado/javascript/assets/134682658/23318928-e038-4130-92f5-c9a25ae31f36)

# TODOS
- [ ] support allowUserRegistration: If set to "true" nothing changes => signup is still available. If set to "false" the login screen should not show a link to "signUp". CorbadoAuth should never show the <SignUp/> component. If the <SignUp/> component used by the developer, we should throw a global error.
- [ ] support userFullNameRequired: If set to "true" nothing changes => both input fields are shown. If set to "false" the <SignUp/> component should not show the input field for username anymore. When we call one of the initSignUpWithXXX functions we should now use the email address for both fields (email and username). 

# Acceptance criteria
- [ ] A change in one of this settings is reflected after a reload of the react and web-js playgrounds
