### ISSUE TITLE
Optimize web-js to be usable also in MPAs (multi page applications, e.g. PHP)

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#177]
# Why

Initially, we developed web-js to be used by SPAs primarily (we didn't explicitly exclude MPAs, but we also never really tested them much). After working on https://github.com/corbado/javascript/issues/166 we should now make sure that vanilla-js can also be used with MPAs by creating one demo PHP application.

# TODOS
- [ ] create a PHP demo application
- [ ] figure out, if we can deploy it to Vercel (if possible, do it)
- [ ] make adaptions to web-js (and the other packages) if needed
