### ISSUE TITLE
Add support for social logins: Google, Microsoft, GitHub

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#178]
# Why
Currently, users can sign up using a passkey or using one of the available fallback options. Some users might prefer social logins to those fallbacks. They can also simplify the sign-up process for those users. Therefore, we now want to add support for three types of social logins: 
- Google
- Microsoft
- GitHub

@corbadoman 
Two TODOs:
1) Please add more details here about the information we will receive from the backend (which social logins are configured for the project, the URLs that we need, when a user clicks on one of the social login buttons)
2) Please explain, what kind of redirects we must handle here in these components.

# TODOS
- [ ] Adjust the StartScreen for signUp and login to show social login buttons, if configured
- [ ] Adjust our init logic (the one that today also handles emailLinks) to handle redirects after the OAuth flow (the protocol behind social logins) has been completed

# Acceptance criteria
- [ ] 3 social login buttons are shown on the StartScreen if configured
- [ ] social logins work locally and on our vercel playground application
