### ISSUE TITLE
Remove the WC from SPA examples

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#179]
# Why
As we don't have dedicated support for Angular, Vue and Svelte yet, we have been using the legacy web component (WC) in our examples and blog posts so far. We now want to remove the WC completely => we must replace it in our blog posts and wizard examples for the previously mentioned technologies.

This depends on #169 and #168 

# TODOS
### Angular (replace with web-js)
- https://www.corbado.com/blog/angular-passkeys
- https://github.com/corbado/example-passkeys-angular
- Wizard

### Vue (replace with web-js)
- https://www.corbado.com/blog/vuejs-passkeys
- https://github.com/corbado/example-passkeys-vuejs
- Wizard
- https://www.corbado.com/blog/bun-passkeys-vue-js

### Svelte (replace with web-js)
- https://www.corbado.com/blog/svelte-passkeys
- https://github.com/corbado/example-passkeys-svelte
- Wizard

# Acceptance criteria
- [x] Wizard is deployed with updated examples
- [x] Blog articles have been updated
- [x] GH examples are updated (on main)

**Comment by vincentdelitz** [comment]
@incorbador done
