### ISSUE TITLE
Remove the WC from MPAs (multi-page-applications)

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#181]
# Why
We must replace the WC in all our blog posts and wizard examples for MPAs.

This depends on #80  
@vincentdelitz please add any other blog articles/examples about multi page applications (like PHP, .NET, Java, ...) that use the WC.

# TODOS
### PHP (replace with web-js)
- https://www.corbado.com/passkeys/php-symfony

# Acceptance criteria
- [ ] Blog articles have been updated
- [ ] GH examples are updated (on main)

**Comment by vincentdelitz** [comment]
@incorbador done. 

If you need access to the GitHub repos let me know. Moreover, to update not only the code but also the blog posts themselves, we should align who can support here (e.g. @lukaskratzel).

**Comment by vincentdelitz** [comment]
@lukaskratzel @incorbador I updated the prioritization of the different frameworks / languages, fyi

**Comment by vincentdelitz** [comment]
@lukaskratzel some feedback for the Node.js blog post
- [x] I think we can remove the docker setup (it's an unnecessary overhead)
- [x] Not sure if the chart on top really has benefit
- [x] Remove the database or do we need it?
- [x] "Corbado Node.js SDK" as consistent naming for the SDK
- [x] 2.2 Is it "Express Backend" or "Node.js (Express) Backend"? If the latter, please name it accordingly (mainly for SEO purposes)

**Comment by lukaskratzel** [comment]
@vincentdelitz Done

**Comment by lukaskratzel** [comment]
@vincentdelitz What's the status here?

**Comment by vincentdelitz** [comment]
@lukaskratzel Java and C# are currently missing. Aleks will take over Java and maybe also C#
