### ISSUE TITLE
Activate PasskeyError screen

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#182]
# Why
Due to limitations of the backend we had to deactivate the PasskeyError screen. We now have fixed that but the fix is currently in beta, i.e. we only roll it out for selected projects. We can activate it first for all our development projectIds. In this issue we want to handle the cases when there is an error during passkey operations or when the operation has been cancelled by the user.

# TODOS
- [ ] Update our flows to handle cancellations and errors in passkey signUp and login
- [ ] Test the PasskeyError screen

# Acceptance criteria
- [ ] Passkey creation during signUp and login flows can be cancelled and repeated from PasskeyCreate, PasskeyBenefits and PasskeyAppend
