### ISSUE TITLE
Signup refactor signup-init screen

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#207]
# Why
Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS
Refactoring the Signup screen according to the screen **S1.1.1, S1.1.2** and **S1.1.3** .
**S1.1.2** shows the maximum expanded page, **S1.1.3** the minimum page (without social login). 

**Social logins will not be implemented yet!**
Error message design is shown in E1.1.1-E1.1.2 and error message texts and icons can be found in the notes next to it. 
- [ ] Refactor the InitSignup including the shadow-effect as shown in screen S1.1.2 and add the effect to every other screen used for user authentication. 
- [ ] Create a user input for username, email address and phone number accordingly to S1.1.1. and S1.1.2.
- [ ] Username input is limited between 4 and 64 character and accept only letters, numbers and "-" or "_" (validation will be done in backend)
- [ ] Email address must be an email address. (validation will be done in backend)
- [ ] Limit the phone number input to a maximum of 13 digits and don't accept any more numbers if max is reached.
- [ ] For the phone number input field add a dropdown to choose the country code and add the country code to the phone number
- [ ] By clicking on the continue button, the button should be disabled and a circular progress indicator is shown on the button.
- [ ] If continue is clicked, every available user input is validated (empty or already taken) an a error message under the according user input is eventually shown. (Error messages and icons can be found in the Figma notes section). 
- [ ] Add error message on top of screen that gets displayed if a signup process was interrupted or a unrecoverable error occurred.
- [ ] For a configuration where it is allowed to sign up with email address **or** phone number add make a swap between email or phone number available according to screen S1.1.1
- [ ] On top of the screen make the AppName text variable and automatically change to the app name of the project. If the name is too long, go to new line and if it's still too long, short it with 3 dots.
- [ ] Add a link to Log in

# Acceptance criteria

- [ ] Screen must display correct input for every possible configuration (Social excluded)
- [ ] Every user input must be validated by clicking on continue.
- [ ] Circular progress indication must be spinning in the disabled continue button.
- [ ] All potential errors can be shown under the according input field.
- [ ] A total signup failure ends at the login screen and shows a message on top of the screen.
- [ ] Add a Brand logo on Top of the page that gets resized if too small or too big. 
- [ ] A customisable text with links is shown on the bottom of the screen, links are highlighted and clickable
