### ISSUE TITLE
Signup refactor passkey-append screen set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#208]
# Why
Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS
Refactoring the Passkey-append screen-set according to screens **S1.2.1-S1.2.8**
**S1.2.7** MethodSwitch screen will not be implemented now!

- [ ] Refactor the PasskeyAppend screen including the shadow-effect according to the Figma screens **S1.2.1** and **S1.2.2** including a placeholder for a graphics with variable size.
- [ ] Add a highlighted field for the email address that includes an letter-icon and a edit icon button.  (S1.2.2. is the same screen but with phone as user identifier).
- [ ] Add to the the  PasskeyActivate screen the possibility to **hide** the user identifier **S1.2.3** and the label above in and show the variation dependent from the path that the screen have been called. (From signup-init with identifier, otherwise without identifier)
- [ ] The user input in screen S1.2.8/S1.2.9 must be validated and error messages and error icons must be shown according to the error screens E1.2.8 and E1.2.9. A cancel brings the user back to the PasskeyAppend screen with no changes made. 

- [ ] Implement a PasskeyError screen according to the Figma screen S.1.2.5 and use the icons described in the Figma note section.
- [ ] Implement/verify the passkey-append process
- [ ] Link all the links and buttons accordingly to the Figma screen-set structure
- [ ] Implement a IdentifierEdit screen **S1.2.8** and **S1.2.9** that can be called from the edit icon button in screen S1.2.1 and that allows the edit of an identifier. The user input for identifier should be pre-filled with the current identifier and a confirm changes the identifier in the identifier field of the screen S1.2.1. 
- [ ] If the email address in screen S1.2.1 is too long, cut it and display 3 dots in the end (adam.santifaller@gm...)

# Acceptance criteria

- [ ] all screens are reachable
- [ ] passkey can be appended
- [ ] user identifier can be edited and validated
- [ ] graphics can be replaced
