### ISSUE TITLE
Signup refacror passkey-appended screen

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#209]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

- [ ] Refactor the PasskeyAppended screen according to the Figma screen S1.3.1 by using the icons listed in the Figma notes section.

# Acceptance criteria

- [ ] The screen can be reached
- [ ] Screen looks like Figma screen S1.3.1
