### ISSUE TITLE
Signup refactor email-verification screen set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#210]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS
Refactoring the Email-verify screen set according to the Figma screen set **S1.4.1 - S1.4.5**

- [ ] Refactor the EmailOtp screen accroding to the Figma screen S1.4.1. Highlighted user email identifier text should be the same as in PasskeyAppend screen.
- [ ] For desktop use, the cursor should already be placed in the first number input. 
- [ ] Implement a Verification code validation that is triggered when the last digit of the code is entered. During the validation a circular progress indicator is visible as shown in Figma screen L1.4.1.
- [ ] If the verification code is wrong, error message and icon is shown accordingly to Figma screen E1.4.1. The code vanishes if it was wrong and the cursor is set to the first verification code input. As soon as a new number is entered in the code input field, the red input field changes again to a grey input field. 
- [ ] Error Message on top of Figma screen E1.4.1 is implemented and is shown if Backend decides that too many attempts of resend a code where made. 
- [ ] Refactor the EmailLinkSent screen according to Figma screen 1.4.2. Highlighted user identifier text should be the same as in PasskeyAppend screen.

- [ ] By landing on EmailOtp page or EmailLinkSent page, the "Resend code" button is disabled and a countdown of **60 seconds** is shown on the button. If the countdown is finished, the button gets enabled and the countdown is not shown anymore. Clicking the button also triggers a short circular progress indication (during the request) before the countdown restarts.
- [ ] EmailOtp screen and EmailLinkSend should both have the option to edit the email by clicking on the edit icon button and be redirected to a EmailChange screen (Figma S1.4.3). It must be also possible to disable the "edit mail" option. 
- [ ] Create the EmailChange screen according to Figma S1.4.3 and by clicking on the Send new code, the user input must be validated (Empty, not an email address, email already exist). Display the error messages accordingly under the input field. Error messages and Icons can be found in the Figma notes section. 
- [ ] Backend can redirect user from EmailLinkSent (S1.4.2) screen to EmailLinkSuccess screen (S1.4.5) if the user clicks on the verification link in the mail.
- [ ] Link in Email opens a EmailLinkSignup page according to Figma S.1.4.4 as loading state. Implement a circular progress indicator.
- [ ] If an error occurs during the SignUp process from the Email link (link or token error) or the link is expired, redirect the user to a EmailLinkError screen according to Figma S1.4.4 and show the appropriate error message. 
- [ ] "Open in Gmail|Yahoo|Outlook" should work as it is implemented right now. 

# Acceptance criteria

- [ ] Verifying a user by verification code over mail
- [ ] Verifying a user by verification link over mail
- [ ] Seeing a circular progress indicator spinning during the verification of the code. 
- [ ] Getting an error if the wrong verification code was entered and instantly being able to try another code.
- [ ] Seeing the countdown of 60 seconds in the Resend code button and only being able to resend a code after the countdown went to 0. 
- [ ] Getting an error on the top of the screen if too many attempts where made to resend a verification code.
- [ ] Automatically being redirected to EmailLinkSuccess screen if email verification link was opened. 
- [ ] During SignUp with email verification link being redirected to EmailLinkSignup and seeing a circular progress indicator. 
- [ ] Getting redirected to EmailLinkError screen if link is expired or wrong. 
- [ ] Being able to change the email address and being alerted if email filed is empty or email already exists.

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
