### ISSUE TITLE
Signup refactor phone-verify screen-set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#211]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Refactor the Phone-verify screen-set according to the Figma screen set **S1.5.1-S1.5.2**

- [ ] Refactor the PhoneOtp screen according to the Figma screen **S1.5.1** including a highlighted user phone identifier text should be the same as in PasskeyAppend screen.
 <! -- - [ ] Add an option to place a brand logo image on top op the PhoneOtp and screen as shown in Figma screen E1.5.1. The maximum possible size should not exceed the size of the logo shown in Screen E1.5.1. -->
- [ ] Implement a Verification code validation that is triggered when the last digit of the code is entered. During the validation a circular progress indicator is visible as shown in Figma screen L1.5.1.
- [ ] For desktop use, the cursor should already be placed in the first number input. 
- [ ] If the verification code is wrong, error message and icon is shown accordingly to Figma screen E1.5.1. The code vanishes if it was wrong and the cursor is set to the first verification code input. As soon as a new number is entered in the code input field, the red input field changes again to a grey input field.
- [ ] By landing on PhoneOtp page page, the "Resend code" button is disabled and a countdown of 60 seconds is shown on the button. If the countdown is finished, the button gets enabled and the countdown is not shown anymore. Clicking the button also triggers a short circular progress indication for a short time (during the request) before the countdown restarts.
- [ ] Error Message on top of Figma screen E1.5.1 is implemented and is shown if Backend decides that too many attempts of resend a code where made.
- [ ] Create the PhoneChange screen according to Figma S1.5.2 Add the same user input for phone as in the InitSignup screen.  By clicking on the Send new code, the user input must be validated (Empty, not an email address, email already exist). Display the error messages accordingly under the input field (E1.5.2). Error messages and Icons can be found in the Figma notes section.
- [ ] In the PhoneChange screen limit the phone number input to a maximum of 13 digits and don't accept any more numbers if max is reached.
- [ ] Add an option to place a brand logo image on top op the PhoneOtp and screen as shown in Figma screen E1.5.1. By a parameter it is possible to align it to left, right or center. to The maximum possible size should not exceed the size of the logo shown in Screen E1.5.1.

# Acceptance criteria

Here you must define the acceptance criteria of this issue (what has to work, what should the developer test and so on). Use TODO checkboxes (markdown).

- [ ] Verifying a user by verification code over phone.
- [ ] Seeing a circular progress indicator spinning during the verification of the code.
- [ ] Getting an error if the wrong verification code was entered and instantly being able to try another code.
- [ ] Seeing the countdown of 60 seconds in the Resend code button and only being able to resend a code after the countdown went to 0.
- [ ] Getting an error on the top of the screen if too many attempts where made to resend a verification code.
- [ ] Being able to change the email address and being alerted if email filed is empty or email already exists.
