### ISSUE TITLE
Login refactor login-init screen

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#213]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Refactor the InitLogin screen according to the screen **S2.1.1, S2.1.2** and **S2.1.3**.
S2.1.2 shows the maximum expanded page, S2.1.3 the minimum page (without social login).

Social logins will not be implemented yet!
Error message design is shown in E2.1.1-E2.1.2 and error message texts and icons can be found in the notes next to it.

- [ ] Create a user input for username and/or email address or phone number accordingly to S2.1.1. and S2.1.2.
- [ ] Use the same input component for phone as used in InitSignup.
- [ ] Limit the phone number input to a maximum of 13 digits and don't accept any more numbers if max is reached.
- [ ] If input field is only for email address, the input must be a valid email address. => this is done in backend
- [ ] By clicking on the continue button, the button should be disabled and a circular progress indicator is shown on the button.
- [ ]  If continue is clicked, the active user input is validated (empty or already taken) an a error message below the input field is eventually shown. (Error messages and icons can be found in the Figma notes section) => this is done in backend
- [ ] As in signup: On top of the screen make the AppName text variable and automatically change to the app name of the project. If the name is too long, go to new line and if its still too long, short it with 3 dots.
- [ ] Add error message on top of the screen that is displayed if a login process was interrupted or a unrecoverable error occurred. Add an error message that is shown, if a error occurs with conditional UI (Errors are shown shown in Figma screen E2.1.1/E2.1.2)
- [ ] Add a link to Sign up

# Acceptance criteria
- [ ] Screen must display correct input for every possible configuration (Social excluded)
- [ ] Every user input must be validated by clicking on continue.
- [ ] Circular progress indication must be spinning in the disabled continue button.
- [ ] All potential errors can be shown under the according input field.
- [ ] A total signup failure ends at the login screen and shows a message on top of the screen.
- [ ] Error while login with conditional UI will trigger an error message on top of the screen.
