### ISSUE TITLE
Login refactor passkey-verify screen-set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#214]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Creating/Refactoring the Passkey-verify screen-set according to screens **S2.2.1-S1.2.3**

- [ ] Create a PasskeyBackground screen according to the Figma screen S2.2.1. 
- [ ] Create a PasskeyError screen according to the Figma screen S2.2.2. Add the UserInfo component to show the identifier (e.g. an email). A click on the edit button break up the login process and brings you to the login screen. The login screen should be pre-filled with the used login identifiers. => @incorbador make backend ready for this.

# Acceptance criteria

- [ ] A login with passkeys must be possible. 
- [ ] All screens must be reachable and look like the Figma screens.
- [ ] Editing the mail brings the User back to a pre-filled login page.
- [ ] Dependent from the path, a user is forwarded to screen S2.2.2 or S2.2.3. S2.2.2 allows a login with Identifier, S2.2.3 allows a jump to Login-complete or email verification. 
- [ ] Links and routs are implemented correctly
