### ISSUE TITLE
Login refactor passkey-append screen-set for login

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#215]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Refactor the Passkey-Append screen set according to the Figma **S2.3.1 - S2.3.3**.

- [ ] PasskeyAppend and PasskeyError screen is exactly the same as the one for signup (S1.2.3, S1.2.5)
- [ ] PasskeyAppended screen (S2.4.1) is exactly the same as the one for signup (S1.3.1)

# Acceptance criteria

- [ ] Passkeys can be appended
- [ ] Passkey-Append process can be retried.
- [ ] All screens are reachable and look like Figma screens.
