### ISSUE TITLE
Login refactor passkey-appended sceen-set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#216]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Refactor the screen-set (single screen) for the Passkey-Appended block. 

- [ ] Refactor the PasskeyAppended screen according to the Figma screen S2.4.1. Use the material icons described in the Figma notes section. 

# Acceptance criteria

- [ ] Screen must be shown when passkey was appended.
- [ ] Continue button brings to Login-completed
