### ISSUE TITLE
Login refactor identifier-verify screen-set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#217]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Refactor the Email-verify for the Login authentication according to the Figma screenset **S2.5.1-S2.5.5** 

- [ ] Refactor the EmailOtp screen according to the Figma screen S2.5.1. The screen is similar to the EmailOTP screen in the signup, except the header text is changed and the edit email action breaks up the login process and redirects to the login init screen. 
- [ ] Refactor the EmailLinkSent screen according to the Figma screen S2.5.2. The screen is similar to the one in the signup, except header and edit email action. 
- [ ] If identifier edit icon button is clicked, user will be redirected to the login screen with pre-filled identifier information. => @incorbador Please prepare API for this.
- [ ] Apply the same "email link logic" for the 2 cases (same and different environment) as in the signup process. Here only the wordings change and can be seen in the Figma screens. 
- [ ] Refactor the PhoneOtp screen according to the Figma screen S2.6.1. The PhoneOtp screen is similar to the PhoneOTP screen in the signup except the header text and the edit phone number action. (Break up login process and return to pre-filled login init screen.

# Acceptance criteria
 - [ ] Log in a user by verification code over mail
 - [ ] Log in a user by verification link over mail
 - [ ] Seeing a circular progress indicator spinning during the verification of the code.
 - [ ] Getting an error if the wrong verification code was entered and instantly being able to try another code.
 - [ ] Getting an error on the top of the screen if too many attempts where made to resend a verification code.
 - [ ] Automatically being redirected to EmailLinkSuccess screen if email verification link was opened.
 - [ ] During SignUp with email verification link being redirected to EmailLinkLogin and seeing a circular progress indicator.
 - [ ] Getting redirected to EmailLinkError screen if link is expired or wrong.
 - [ ] Breaking up the login process if clicking on edit email address icon button and being redirected to the login screen with pre-filled out identifier.
