### ISSUE TITLE
Login refactor phone-verify screen-set

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#218]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

Refactor the Phone-verify screen-set according to the Figma screen set S2.6.1-S2.6.2

- [ ] Refactor the PhoneOtp screen according to the Figma screen S2.6.1. User input, error messsages and identifier field is identical to PhoneOtp screen for signup. Identifier edit icon button must only be available if path is coming from Login-init.
- [ ] Add an option to place a brand logo image on top op the PhoneOtp screen as shown in Figma screen S2.6.1 and E2.6.1. By a parameter it is possible to align it to left, right or center. to The maximum possible size should not exceed the size of the logo shown in Screen S2.6.1 and E2.5.1.

# Acceptance criteria

- [ ] Login or verifying a user by verification code over phone.
- [ ] Seeing a circular progress indicator spinning during the verification of the code.
- [ ] Getting an error if the wrong verification code was entered and instantly being able to try another code.
- [ ] Seeing the countdown of 60 seconds in the Resend code button and only being able to resend a code after the countdown went to 0.
- [ ] Getting an error on the top of the screen if too many attempts where made to resend a verification code.
- [ ] Being able to change the email address and being alerted if email filed is empty or email already exists.
- [ ] Add a Brand logo on Top of the page that gets resized if too small or too big and can be aligned left, centre, right.
