### ISSUE TITLE
make icon color for passkey list component adaptable

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/javascript#228]
**Background**
Currently the passkey icon on the very left and the delete icon on the very right are always is black. Currently, it's almost not visible for users

**TODO**
 - [x] Can we introduce two color modes for these icons as well: One for light and another one for dark mode
 - [x] The general passkey icon + delete icon should be then in white or black (depending on the mode).
 - [x] Also for individual AAGUIDs, there are icons for light and dark mode, see here: https://github.com/passkeydeveloper/passkey-authenticator-aaguids/blob/main/aaguid.json. Can we please also use the right icons for light and dark (if you need help on downloading the files properly, please contact @vincentdelitz)
