### ISSUE TITLE
Signup refactor email-verification link

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#234]
# Why

Moving from a fixed structure with an atomic request to a dynamic structure build with blocks and according screen-sets.
Blocks and screen-sets are defined and designed in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271-10&mode=design) page.

# TODOS

- [ ] Refactor the EmailLinkSent screen according to the Figma screen S1.4.2. Use the same user information component and make the email address it editable, same as the EmailOTP screen.
- [ ] Use the frontend-API to get information about the environment, in that the email verification link is opened. 
- [ ] If the email verification link is opened in the same environment as the EmailLinkSent screen, the EmailLinkSent screen must automatically be redirected to the EmailLinkSuccess screen (S1.4.5), and the signup must continue in the new tab. 
- [ ] If the email verification link is opened in a different environment, the link should be redirected to the EmailSuccessScreen (S1.4.6) and the tab of EmaiLinkSend should be used to continue the signup process. 
- [ ] Add the error screen EmailLinkError (E1.4.4.1, E1.4.4.2). If the link is expired, show the error message shown in E1.4.4.1, for any other error show the error screen E1.4.4.2. 

@incorbador, please add the technical part
