### ISSUE TITLE
Missing Tasks for Component Release

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#242]
# Why
Please find screen design and information in [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271%3A10&mode=design&t=d3EM73jdszjAVyiQ-1)

# TODOS
Prio 1
- [x] Make all screen the same width of 400px (should already be) and adaptable until 300px width. 
- [x] Add theme for components
- [x] Refactor the NonRecoverableErrorForCustomer screen according to the Figma Screen S0.1.2.
- [x] Remove the Terms and conditions in the Signup Screen
- [x] For signup in the passkey append block, allow to edit the username. Use the IdentifierEdit screen and change wordings and error messages according to the Figma screen S1.2.10 and E1.2.10.
- [x] Conditional UI Errors:
       - For a relying party ID Error (config error) show the top error with unable to complete this action
       - For a invalid passkey error, show a error below the input field according to the Figma screen E2.1.1/E2.1.2. Error message: "The provided passkey is no longer valid. Please enter your identifier (e.g. email) manually. "
- [x] Change text sizes according to Figma screen S1.3.1 (is same as S2.4.1) PasskeyAppended screens in Signup and Login. 
- [x] Error message in Signup username field when Username is just two characters long: "Username must be between 4 and 64 characters long." (right now is "Username can only contain letters, numbers and “-” or “_”)
- [x] In signup, passkey append block for the PasskeyError screen (Figma S1.2.5), change the separation text from "or" to "Or continue with".
- [x] For every screen that contains a "or" separation, remove the or separation, if no fallback is available. (E.G. Only username allowed for signup -> Something went wrong screen)

**Comment by Adam3371** [comment]
All tested
