### ISSUE TITLE
web-core & react-sdk: email OTP sign up

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#25]
### Why
When signing up to Corbado users should go through an email OTP (one-time password) flow. After completing this flow the user has proven that he has access to that email address. An account is created for him and he is logged in. 

**The flow looks like this:**
- user provides his email address
- Corbado Backend sends a 6 digit code to the user's email
- user provides the correct code and is logged in

### TODO
- [x] create web-core functions to start and finish email OTP sign up
- [x] create React hooks that wrap these two functionalities in react-sdk
- [x] finishing email OTP sign up returns two tokens (shortSession + longSession) => they must be stored and should be accessable through the react-sdk

### Acceptance criteria
- react-sdk example that shows working email OTP sign up (very simple UI)
- auto-generated HTTP client is used in web-core

### Implementation idea
- create initSignUpWithEmailOTP and completeSignUpWithEmailOTP in web-core 
- create React hooks (initSignUpWithEmailOTP, completeSignUpWithEmailOTP, getUser)
- build a small react-sdk example to test if react-sdk hooks are working
