### ISSUE TITLE
Missing features for components

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#250]
# TODOS

Prio 1:
- [x] Change the Corbado badge by removing the Corbado icon + Corbado text SVG and simply extend the "Secured by" to "Secured by Corbado". Change the in badge height to 1.6rem and the width to 9rem. (Shown in the image)
- [x] Change Icon for PasskeyError screen in passkey-verify block with [this](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aperson%3A) icon. For PhoneOTP screen change the mail icon with [this](https://fonts.google.com/icons?selected=Material+Icons+Outlined:phone:) icon
- [x] Add pre-filling in the signup screen, the BE already provides the information.

 Country code selector for phone:
- It is okay if the country code is in the input field (like on the upper one)
- We don't add a input field in the dropdown list yet.
Prio 1:
- [x] A selection of the country should not trigger an API call
- [x] Check that auto-complete option and pasting (if correct formatted) phone numbers work.
- [x] Check that the style is correct. (Can't always see the complete border of the input field)
- [x] Enter in the phone number field triggers the "Continue button".
- [x] The max. phone number length should be (without country code) 13 digits.

**Comment by Adam3371** [comment]
@Aby-JS 
After testing current code country selection, this points are still open (Highest to lowest prio):
- [x] On Android, there is a very strange behaviour when deleting: browser jumps in front of the '+' sign and adds the country code after the country code
- [x] On iPhone 10 and iPhone 13 on safari, chrome and the slack application browser the input field looks like in the picture
- [x] On iPhone autocomplete option is only shown if you manually place the cursor in front of the "+" sign, autocomplete is not working
- [x] Phone number should not disappear if changing country code
- [x] Enter in a empty phone number field opens the list, in a filled field triggers continue button
- [x] Make "+1 (USA)" country code as default and fallback (if no information is provided from the country code)
- [x] Add a "arrow down" [icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aarrow_drop_down%3A) on the right side of the flag in the code country selector
- [x] Make the background a little bit darker (F5F5F5)


![image](https://github.com/corbado/javascript/assets/56920624/f461a1b2-471a-4c43-9773-26e493b6de1a)

**Comment by Adam3371** [comment]
Follow up:
- [x] For the web-js example [application](https://feature-refactor-to-thin-frontend.web-js.playground.corbado.io/auth.html) in mobile view the size of the components are too small (not the same as for the react example application).
Check if it's a component problem or a problem of the hosting page and fix the issue. If it's a component problem, report it. 
- [x] In web-js in logged-in state the passkey-list theme is dark and not constrained to a width. Fix the passkey list theme and size and check if the themes in web-js are general correct.
- [x] For the EmailLinkSuccess screens in Signup and Login, change the icon to this [icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Acheck_circle%3A). The screens should look like the screens S1.4.4, S1.4.6, S2.5.5, S2.5.6 in the [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271%3A10&mode=design&t=snuhjHtf92cIazv7-1) 
- [x] For the EmailLinkError screens change the style around the icon. The style should look like the screens E1.4.4.1, E1.4.4.2, E2.5.4.1, E2.5.4.2 in the Figma.
- [x] In the IdentifierEdit screens (For email, phone, username) implement a function, that if cursor is in the input field and pressed "enter" and the confirm button is enabled, it triggers a the "confirm" command. If the "confirm" button is not available, nothing happens when pressed enter.
