### ISSUE TITLE
React: email OTP sign up

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#26]
### Why
In #25 we created React logic to sign users up through email OTP. We now build the required UI components.

### TODO
We only create components here, no redirect logic (this is done #12 )
- [ ] build form for name + email (1.1)
- [ ] build email OTP screen (email icons are static and open email clients in current browser) => ignore the "Send one time code again" for now
- [ ] if the code is wrong an error is shown and the user can try again
- [ ] redirect to "redirect url" 

<img width="444" alt="image" src="https://github.com/corbado/javascript/assets/134682658/1a35584a-1cad-4b24-b342-68908ae0f416">
<img width="328" alt="image" src="https://github.com/corbado/javascript/assets/134682658/6f5cc09e-dc78-4834-bfa3-65eb1ed58df5">
<img width="439" alt="image" src="https://github.com/corbado/javascript/assets/134682658/c1e1e9f1-3694-4827-a475-d63c0e123d34">

### Acceptance criteria
- React example that shows working email OTP sign up, it should use the React sign up component and redirect the user to a LoggedIn page
- the LoggedIn page should show the user's name and email address

### Implementation idea
- build CorbadoAuth React component (this component can contain sign up and later also sign in)
- build a small React example to test if React UI components are working
