### ISSUE TITLE
Auth component polishing

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#261]
# Why
During testing, we found a few more things we want to improve (they mostly affect styling).
This ticket is currently work "in specification".

# TODOS
- [x] Adjust design of OTP input fields for Firefox. (React, Web-js, DevPanel and all Demo applications)
- [x] vertically center the "!" icon for InputField errors
- [x] "!" icon is too small for long error messages (e.g. when the error message has two lines) => screenshot 1
- [x] allow copying OTP codes on mobile (error has been found on Android)
- [x] If a error defined in [this ticket](https://github.com/corbado/corbado/issues/3181) is thrown from the FAPI, add a top-error message "This app requires passkey authentication. Please use a compatible device.".
- [x] In passkey append screen for signup and login, a user should be able to trigger the append process by pressing the "enter" key.
- [x] In passkey appended screen for signup and login, a user should be able to confirm by clicking the "enter" key.

![image](https://github.com/corbado/javascript/assets/134682658/b474ff5b-2fda-41d4-ab87-f3eac68cef7f)

We moved this out of scope of this ticket:
- improve alignment of the email icon buttons on EmailOTP screen @Adam3371 can you check with Vincent if the Figma is ok pls?

**Comment by incorbador** [comment]
Here a screen recording for "allow copying OTP codes on mobile (error has been found on Android)":

https://github.com/corbado/javascript/assets/134682658/e9e5a589-0aaa-45da-9c53-e207a7673977

**Comment by incorbador** [comment]
Regarding email alignment: Let's remove this point from this issue as we have to deal with email buttons in #276 anyway.

**Comment by Adam3371** [comment]
Tested:
OTP paste/autocomplete on Andoid woks fine!
Top error message with no fallback settings and no passkey support browser is not shown correct. 
- Signup screen: changes to login screen and shows "This error is not being handled by the frontend: undefined (process_can_not_be_completed)"
- Login screen: Works fine
