### ISSUE TITLE
Remove the Unused codes and styles

### ISSUE THREAD

**Issue by Aby-JS** [corbado/javascript#265]
# Why

We need to remove the unused old react-sdk package, react components, shared-ui styles and also refactor the new styles.

# TODOS

- [x] Remove `react-sdk` package and move the `useCorbado` hook and related contexts to react package.
- [x] Delete unused components in react package.
- [x] remove the old styles from `shared-ui` package.
- [x] Refactor the new style sheet by breaking it into multiple style sheets and go through all the names of CSS classes and check if they follow the naming convention properly

# Acceptance criteria

- [x] No dependency on `react-sdk`
- [x] Well organized stylings in `shared-ui`
- [x] All functionalities are working as they were before changes

**Comment by incorbador** [comment]
yes makes sense, we should first merge feature-refactor-to-thin-frontend to develop
