### ISSUE TITLE
Add changelogs for react and web-js

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#269]
# Why
We want to make changes in our packages transparent for external developers. This is important the two packages that are used publicly: react and web-js.

# TODOS
- [x] Suggest a format that we want to use in those CHANGELOGs and agree on it with Adam and Martin
- [x] Add one CHANGELOG.md file for react and another one for web-js
- [x] Link to those changelogs from our READMEs

# Acceptance criteria
- [x] Changelogs include information about changes in v2.0.0 packages
- [x] Changelogs can be reached from READMEs on Github
- [x] Changelogs can be reached from npmjs

**Comment by incorbador** [comment]
Feedback:
- you added one changelog.md, I think we should have one CHANGELOG per public package though (i.e. one for web-js and one for react => please take a look at the ticket, I mentioned this here as well)
- I think we should document the last 3 stable versions (1.1.14, 2.5.4 and 2.6.0 => this one should include client state and routing component init changes and still needs to be released)
- If you need help from me for certain tasks just mention me in those parts => then I can add additional details there
- I think we should group changes into three categories: Major, Minor and Patch (see example below)

## 2.6.0
### Minor changes
- Added one-click "signin with passkey" button
- Improved state management when component is refreshed => allow the user to reset the authentication process by navigating to the initial URL where the process has started
- ...

## 2.5.4
### Major Changes
- Social logins are now available (Google, Microsoft, GitHub)
- Added support for email-links, phone-otp and username
- Hash URL Navigation: Introduced hash-based URL navigation to better manage the signup flow state, ensuring that refreshing the page does not lose the user's current progress.
- Breaking change: Restructured translation files (see docs: <link>)
- Breaking change: Restructured custom themes (see docs: <link>)
- Hash URL Navigation: Introduced hash-based URL navigation to better manage the signup flow state, ensuring that refreshing the page does not lose the user's current progress
- New UI Design: Enhanced layout with more customizable CSS variables and classes, making it easier to modify the appearance and feel of the application
- ...

### Minor changes:
- Dark Mode Icons: Improved support for icons in dark mode, enhancing visibility and user experience in low-light environments
- ...
