### ISSUE TITLE
Feature and Bugs backlog

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#282]
# Why
Improve the 

- **R** Components
- **W** Web-JS
- **D** Dark Mode specific
- **DevP** for developer panel
- **A** All

# TODOS

Abdullah:
- [ ] Back link-text in all screens [A]
- [x] Make email otp screen without email shortcut same style as phone otp screen
- [x] Set cursor automatically to input field in the signup [A]
- [x] Sub-Headline normal font weight [RD]
- [x] Input-field border color #D4D4D4
- [x] Hover color: Add opacity
- [x] Change disable color for all components
- [x] Make Email, Phone, User icon in dark mode white
![image](https://github.com/corbado/javascript/assets/56920624/573c0ae0-f1e8-40b6-a598-ff5e7a5fc24a)

General
- [ ] [Safari issue](https://github.com/corbado/javascript/issues/275)
- [ ] Cancel/fallback in Passkey verify screen
![image](https://github.com/corbado/javascript/assets/56920624/26cb913f-bab9-4e87-9087-0b393832c179)
- [ ] Can we add a timeout if no API call made in the verify screen?
- [ ] Back link-text in all screens [A]
- [x] Remove "Back Navigation" in Signup and Login screens. [A]
- [ ] Remove/Improve passkey append screen [D/A?]
- [x] Make email otp screen without email shortcut same style as phone otp screen
- [x] Set cursor automatically to input field in the signup [A]
- [x] Change hover color (screenshot 1)[D/A?]
![image](https://github.com/corbado/javascript/assets/56920624/1141033f-f49b-44c9-aa7a-0563e4dcbc59)

Component design in [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6868%3A1950&mode=design&t=D3Iy36svcogTeSve-1):
- [x] Sub-Headline normal font weight [RD]
- [x] Input-field border color #D4D4D4
- [x] Hover color: Add opacity
- [x] Error text color add opacity
- [x] "or" separation line: add opacity to "or" color
- [x] Change icon of "Abort signup dialog"
- [x] Change disable color for all components
- [x] Make Email, Phone, User icon in dark mode white
![image](https://github.com/corbado/javascript/assets/56920624/573c0ae0-f1e8-40b6-a598-ff5e7a5fc24a)

Phone Input 
- [ ] USA, Germany, India, GB on top
- [ ] Auto country code select
- [ ] Don't allow other characters than "+" and digits
- [ ] Round a bit the list and add stroke around
- [ ] Search field always stays on top
- [ ] Thinner separation lines
- [ ] Make selection fully possible with keyboard
- [ ] Easy navigation with enter/arrows
- [ ] Error message for phone number

# Acceptance criteria

Here you must define the acceptance criteria of this issue (what has to work, what should the developer test and so on). Use TODO checkboxes (markdown).

- [ ] ...
- [ ] ...

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
