### ISSUE TITLE
Remove back navigation option in Signup and Login screen.

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#283]
# Why
In the signup and login process we currently catch every "back navigation" event and show a "Abort Signup/Login?" dialog. 

This "back navigation" event is also tracked in the signup and login screen, but here a "Abort Signup/Login?" dialog makes no sense because there is nothing to abort.

# TODOS
- [x] Remove the "back navigation" event tracking for the signup and login screen.
- [ ] Add the new functionality (removing of back navigation tracking) to the dev panel.

# Acceptance criteria

- [ ] A user should be able to return to the page where he is coming from by just navigating back.
(E.g. corbado.com -> app.corbado.com -> "back navigation" -> corbado.com)

**Comment by Adam3371** [comment]
We have defined some overall rules for back navigation that we should implement for the signup flow:

- In every block, the screens should be stacked and a back navigation should be possible without obstacles until the initial screen in the block
- It is possible navigate back between the blocks, if the blocks are stacked in the block view vertically. (see [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6271%3A10&mode=design&t=4vxCf9r4OSJLmTBE-1)
- A "abort signup" dialog should be triggered, if the a user wants to leave a block horizontally. The init-signup block is here an exception.
- Navigation between login-init and signup-init screen should be stacked and back navigation is possible without obstacles.

## TODOS
- [x] Change the code in order that for every block, a simple back navigation is possible until the initial screen of the block.
- [x] Rollback the code change in order that is possible to simply "navigate back" between blocks stacked vertically.
- [x] Only if a user wants to exit the block, show the "Confirm Abort" dialog. 
        - By clicking on "Yes, take..." the signup process is interrupted and the user is taken to a pre-filled signup screen
        - By clicking on back, the user returns
        - By "navigating back" using the browser arrows, the user is taken back to the signup process (as it would press on back)
        
- [x] Changes between signup and login should be stacked on the navigation history and a "navigation back" will just show the previous screens. (Normal back navigation)

**Comment by Adam3371** [comment]
Tested 
Some minor issues
- [ ] When ending in "Abort Signup" dialog and navigating back again, user should be taken to the screen where the "Abort Signup" was triggered. (Same as if the user would click on the  "back" button in the "Abort Signup" dialog)
- [ ] In passkey-append, emailOTP and phoneOTP screen, when editing the identifier and navigating back, the user is shown a "abort signup" dialog. (Should navigate back to the passkey-append screen)
- [ ] In passkey-append screen when ending on passkey-error screen, a back navigation should bring the user to the passkey-append screen. (Currently it shows the abort signup dialog)

Email magic link coming soon
