### ISSUE TITLE
Improve style of components in different themes

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#284]
# Why
In this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=6868%3A1950&mode=design&t=D3Iy36svcogTeSve-1) page in the "Final" section you can find design improvements for the components. 

# TODOS
Adjust component style for **React** and **WebJS**

- [x] Change sub-headline to regular font weight
- [x] Align the top error text+icon to the input field and button by adding the same vertical padding as for the rest of the component and resize the warning icon to 20x16px. (See Figma design)
Ensure that the top error styling follows the rule for every error message of every length
- [x] When opening the signup screen, set the cursor automatically to the uppest input field (same as for login)
- [x] Adjust the style of the Email OTP without Email shortcut and Phone OTP according to the Figma.
- [x] Adjust background of OTP input fields when full code is entered. (To discuss with adam) [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=9255%3A2453&mode=design&t=FINB3eKMSJT3KNXi-1)

Light mode
- [x] Change the input field border color to #D4D4D4
- [x] Change the hover color of the button to #1953FF + opacity of 0.75
- [x] Change the "or" separation text and line color to #000000 + opacity 0.75
- [x] Change the disabled color to #DFDFE0
- [x] Change the Icon color of email and phone and user (passkey error screen) to black. 

Dark mode
- [x] Change the input field border color to #848CA6
- [x] Change text color to #A1A1A1 (except Title and subitle)
- [x] Change the hover color of the button to #1953FF + opacity of 0.5
- [x] Change the "or" separation text and line color to #ffffff + opacity 0.75
- [x] Change the disabled color to #6F7486
- [x] Change the Icon color of email and phone and user (passkey error screen) to white. 
- [x] Adjust the Top Error background color to #5B5B6B

Developer panel
Adjust hover color for email shortcuts according to Figma. (Color #525D83) => Moved to this [ticket](https://github.com/corbado/corbado/issues/3230)

**Comment by Adam3371** [comment]
Update 
- [x] "Space Grotesk" font-weight issue in react
- [x] Button disabled color is not as shown in Figma (Lightmode #DFDFE0 Darkmode #6F7486)
- [x] Change top error text color in light mode to color #4D5562
- [x] In dark mode, primary (or secondary) color on every other screen is grey instead of white
- [x] If possible, make the border of the input fields thinner
- [x] Make "or" separation less heavy (clarify with Adam)
- [x] In dark mode change text color inside the input field to white

**Comment by Adam3371** [comment]
Update
- [x] In darkmode keep the color of the main text and the icons of all the other screens white (screenshot 1, if you need clarification ask adam).
- [x] In white mode change the hover color of the social buttons and email shortcut button to RGB(245, 245, 245, 100)
- [x] If no much time required, in darkmode change the country code color to white and in the dropdown change text and country code also to white

screenshot1
![image](https://github.com/corbado/javascript/assets/56920624/0068faea-3e69-4062-9c86-18ffad5eca66)

**Comment by Adam3371** [comment]
- [ ] In darkmode change the text of the identifier to fully white instead of grey. (It's not a problem if the identifier text in the passkey-append screen is also white)
