### ISSUE TITLE
Add "use other method" button to PasskeyBackground screen. 

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#287]
# See last comment

# Why
We need to provide an alternative on the PasskeyBackground in the PasskeyVerify block in case that something goes wrong and the passkey challange cannot be completed. (E.g. Safari is sometimes not making an API call after fingerprint is entered and user is stuck in the passkey background screen)

# TODOS

- [ ] In PasskeyBackground add a "Use other method" link text
- [ ] If clicked on the link text, the PasskeyError screen should open, but the title should be "Use other method". 
- [ ] Authentication flow should proceed the same as if landing on the PasskeyError screen

**Comment by Adam3371** [comment]
Changed task.

If information available, provide directly the fallback options (Use email verification, use phone verification) instead of "Use other method".

**Comment by Adam3371** [comment]
passkey-background escape missing linebreak when having 2 fallback options

**Comment by Adam3371** [comment]
@incorbador is currently working to stop the passkey ceremony (e.g. windows hello) if a fallback option is selected manually. 
If the problem can be solved
- [ ] In passkey append screen during the passkey ceremony enable the fallback options

**Comment by Adam3371** [comment]
# Why (Update)
We currently have to deal with 2 different issues on 2 different browsers:

1. On Mac the Safari browser can reach a state, where no API call is triggered after the biometrics (fingerprint) are entered. Since the passkey-verify screen have no fallback options, this can lead to a broken state where the user is locked in the passkey-verify, passkey-append or passkey-error screen after entering the biometrics.
2. On Windows on any browser if a user have stored a lot of passkeys, it can take a long time (up to 10 seconds) until the windows hello authenticatior is opened. Sine we need to provide a fallback option in the passkey-verify screen to avoid issue 1, a user on windows can click on the fallback option during the time that the Windows Hello needs to open. This can lead to a situation where the user is in a fallback option (e.g. email OTP) and Windows Hello is then opend. We need avoid to handle a Windows Hello input if the user is already in a fallback state. 



# TODO
Currently in the "passkey-verify-background-escape-with-cancel" branch, there is a solution for avoiding to handle further inputs of authenticators (windows hello, macOS authenticator ect.). Continue the implementation on this branch.

- [ ] Enable the fallback link texts (Use email verification, use phone verification) for following screens and  **allow only one click and avoid multiple clicks on the fallback link texts**.
    In Signup process:
    - [ ] Passkey append (Both also for maybe later)
    - [ ] Passkey error
    In Login Process
    - [ ] Passkey-verify (already implemented but allow only one click)
    - [ ] Passkey append 
    - [ ] Passkey error
