### ISSUE TITLE
Social login improvements

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#292]
# Why
After our first implementation of social logins we now need to improve a few things in our frontend (mainly react package and shared-ui).

# TODOS
- [x] Social buttons styling on initial screen (background, background:hover, margin between text and icon). See [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=9201%3A8372&mode=design&t=slUNTEPX8NLP4uQ4-1) draft
- [x] Animate social buttons after they are clicked and disable other buttons (similar behaviour as when the user click the "login" button
- [x] Add title to social buttons ("Sign in with {{providerName}}") => we don't need to add this to translations, having this in English only is fine
- [x] Icon in top error is not correctly aligned (reproduce: start social login but cancel it by not consenting)
- [x] Update IdentifierList component to show SocialAccounts (/me endpoint already returns the data) according to [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=9201%3A8371&mode=design&t=slUNTEPX8NLP4uQ4-1)

**Comment by Adam3371** [comment]
- [ ] Login or Signup with social and then cancel the process, the user is taken back to a infinity loading init screen. (Continue button is disabled and social button is loading)
![image](https://github.com/corbado/javascript/assets/56920624/34e4601a-5d0f-4584-99bc-11fc7a1ffe30)

- [ ] Creating an account with social from the login screen triggers an error.
=> @incorbador is taking care of the BE 
=> @Aby-JS ensure that the user-state in the  login/signup screen is not in an "endless loop".
![image](https://github.com/corbado/javascript/assets/56920624/38514a67-e7f8-421e-bd1e-bc17eb0220d4)

**Comment by Adam3371** [comment]
@Aby-JS 
- [ ] Error messages should disappear after refreshing the page or after changing between signup and login. 
- [ ] If the "This error is not being handled..." error appears, a switch to Signup is not possible. (Even if this error will be resolved, ensure that a error like this is not causing the user to be in an endless state)

**Comment by Aby-JS** [comment]
@incorbador what can we do about the point:
`Error messages should disappear after refreshing the page or after changing between signup and login.` as the BE returns this point even after page refresh
