### ISSUE TITLE
Adjust text color in dark-mode for login/signup screens.

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#309]
# Why
This is a follow up ticket of the "improve style of component" [ticket](https://github.com/corbado/javascript/issues/284) to fix a minor issue with text color in dark mode.

# TODOS
- [x] For Signup and Login screen in dark-mode, change the text color of the texts above the input fields (email address, phone number, username) from white to rgba(161, 161, 161, 1)
- [x] Ensure that only the text color for the Login and Signup screen is changed and the changes does not affect the other screens.

# Acceptance criteria

- [x] Make sure that the screes drafted in [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=8739%3A648&mode=design&t=DkwyRUqgwKvSgR9l-1) resemble the screen of the components. (only the available)
