### ISSUE TITLE
Update component state when user interface settings are changed

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#313]
# Why

In order to provide the best DX, in developer mode the state of the component should be changed when a refresh occurs if a setting in the developer panel was changed. This change of component state should change also if fields are pre-filled.

# TODOS

- [ ] If a user is in the InitLogin or InitSignup screen (only there) and a setting i changed in the User interface settings, the components should resemble the changes.

- [ ] If fields of the component are pre-filled and a setting is changed (only then), clear the pre-filled values at the first refresh and clear the component state.
 Alternative:
 - Add or remove new fields and leave the pre-filled fields filled. 

# Acceptance criteria

- [ ] A change in the settings can be seen in the component by simply refreshing the page (preview, demo), no matter if fields are filled or not.  

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
