### ISSUE TITLE
Improve passkey-error screen

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#317]
# Why

In the passkey-error screen currently the "Try again" ist the CTA and the "Continue with .. " is not prominent enough. The theory is that this might confuse the user. Therefore we want to swap the content of the CTA with the link at the bottom of the component.

Change the passkey-error screen according to the draft in the [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=9766%3A7930&mode=design&t=3pg9hn8cMeTQqQ9k-1)

The passkey error screen can be found in the following blocks:
- Passkey-append 
- Passkey-verify 

## TODOs:
- [ ] In the passkey-error screen change the CTA to "Continue with XXX" where XXX is the primary identifier (email or phone).
- [ ] If 2 primary identifier/fallsbacks are possible, use always email as higher priority (the other identifier is NOT shown as an option then)
- [ ] Change the linktext below the "or" separation to "Try again".
