### ISSUE TITLE
Evaluate social login test for microsoft

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#324]
# Why

Currently we don't include social logins in our Playwright tests.
Ideally, we want to test at least the happy paths here.
We already found out that it is hard to write e2e tests for Google and GitHub so we want to evaluate if it's possible for Microsoft.

# TODOS
- [x] Create a MS account
- [x] Write a basic e2e test that goes through a social signup using MS
- [ ] Extend test (only if the previous two steps worked)

**Comment by aehnh** [comment]
Social login is no longer supported on staging (and local) deployments. (social login configs are also absent in the dev panel)

Redeploying staging, as well as merging main into staging1, did not work.

**Comment by aehnh** [comment]
Automated playwright testing on microsoft social login works without problem so far.

Signup test done, working on login test
