### ISSUE TITLE
Split Playwright tests into two groups

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#325]
# Why

Running all e2e tests on every commit to a PR takes too much time and resources.
It would be better to split the existing set of tests into two groups:
1. runs every commit to a PR
2. runs every night

# TODOS

- [x] categorize tests into the 2 groups (only functionality tests only on chrome for every commit)
- [x] check if playwright provides a native way to group and run tests selectively
- [x] update github action to run the task every night
- [x] evaluate time speedup (~5 minutes per commit)
- [x] find a way to notify developers upon errors on nightly run (e.g. slack)

**Comment by aehnh** [comment]
https://ray.run/blog/organizing-playwright-tests-using-tags

I can tag specific tests and run only those on CLI command.

I still need to check how I can limit these tests to run only for Chrome.

**Comment by aehnh** [comment]
There is no way to use tags to specify browsers. However, it seems reasonable to remove any browser specifications from the config file and simply specify browsers for the entire test set from CLI command. The downside would be that the nightly tests would take slightly longer (because even tests that were originally intended to be run on only chromium would run on every browser) but taking 20 minutes instead of 15 minutes for each nightly run seems rather trivial

**Comment by aehnh** [comment]
https://github.com/vercel/vercel/issues/10550

Apparently cron github jobs only work on production..

**Comment by aehnh** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

Github cron jobs run only on the last commit of the default branch (develop on corbado/javascript repo)

**Comment by aehnh** [comment]
Keeping it at in-progress until I confirm that the nightly workflow runs properly on develop branch

**Comment by aehnh** [comment]
Also need to search about slack notifications

**Comment by aehnh** [comment]
https://github.com/marketplace/actions/slack-send

**Comment by aehnh** [comment]
https://github.com/ryanrosello-og/playwright-slack-report
