### ISSUE TITLE
Mising `passkeyAppend` functionality from `useCorbado` hook

### ISSUE THREAD

**Issue by Aby-JS** [corbado/javascript#331]
# Why

We need to export another function from `useCorbado` hook which allows developers for append passkeys to currently logged in customer.

# TODOS.

- [ ] Export a `passkeyAppend` function from `useCorbado` hook and from web-js package's global `Corbado` object

# Acceptance criteria

- [ ] User can now append passkey for their authenticated users using a button in their React application.
- [ ] User can now append passkey for their authenticated users using a button in their Vanilla JS application.
