### ISSUE TITLE
Fix e2e tests after changes on PasskeyError screen

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#332]
# Why
Our changes on the PasskeyError screen broke a few of our e2e tests. As these tests are stable now (two concurrent runs no longer interfere with each other), we should fix them

# TODOS
- [ ] Run the failing tests locally to reproduce the errors
- [ ] Fix the failing tests (probably we can explain all these failing tests by the fact that we have swapped the two buttons on the PasskeyError screen)
- [ ] In case you face problems with the e2e tests locally or in the pipeline, feedback @aehnh or @incorbador 

# Acceptance criteria
- [ ] Tests are green in the pipeline
