### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by Aby-JS** [corbado/javascript#347]
# Why

We see alot of `%` (percentage) based size stylings in our current CSS. These are generally hard for developers to improve and make a definitive size change if required in the future,

# TODOS

- [ ] Find the styles using `%` based sidings and see if a definite size with `rem` can be used instead or atleast if the size can be calculate with `calc` making it easier to change in the future.
- [ ] Look for other refactoring possibilities to improve readability of stylings

# Acceptance criteria

- [ ] No visible change in the UI after stylings have been refactored

**Comment by incorbador** [comment]
I think the percentages by them selves are not a problem. The issue I see is that we repeat them quite a few times in our code ("width: 90%;" is repeated 9 times, in total we have to specify the width attribute quite often) => So for me the important question is: Can we structure the layout in such a way that we don't rely so much on magic width numbers like "90%" or "5.25rem"?
