### ISSUE TITLE
Add second passkey-error screen to login flow

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#349]
# Why

We want to introduce a 2. version of a passkey-error screen in order to have a **PasskeyError** and a **PasskeyErrorLight** screen. This allows to show a non-error like screen if a user aborts the passkey-verify process by fault or the iOS gesture bug occures. 
Only at the second passkey-abort/error, a real error message is shown.

A draft of screens and flows can be found in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=10336%3A3702&mode=design&t=f4Tm1KVdd11F5jPB-1).

# TODOS
Before you start: check implementation idea below

- [x] Create a new passkey-error screen according to the Figma draft "S2.2.3 PasskeyErrorLight". The screen should not variate too much from the passkey-error screen except Title, Icons, Text and CTA and Secondary button are switched from the current passkey-error screen.
- [x] Show the "PasskeyErrorLight" screen at the **first** error/abort of a passkey-verify process. 
- [x] If a user clicks on "Login with passkey" button, the authenticator should open on top of the PasskeyErrorLight screen. 
- [x] If a second error/abort is triggered during the passkey-verify process, the normal PasskeyError screen (Figma draft S2.2.2 PasskeyError) should be shown. 
- [x] The PasskeyError screen should continue to work as usual.
- [x] If a user is navigating back or editing the identifier, the error screen order resets and the user starts from the beginning.

Additional changes
- [x] Adjust the "or" separation line to match the width of the CTA button. (Screenshot 1)

# Acceptance criteria

- [x] First passkey-error/abort shows the user the PasskeyErrorLight screen
- [x] Second passkey-error/abort navigates the user to the normal PasskeyError screen
- [x] User that returns to the LoginInit screen, restarts with the process.
- [x] "Or" separation line have the same width as the CTA button

# Implementation idea
@incorbador => Please add additional implementation hints, like create another screen or just change the wordings.

# Screenshots
![image](https://github.com/corbado/javascript/assets/56920624/2f225ae6-6cfa-4a36-95ea-f7339444c3ee)

**Comment by Adam3371** [comment]
Tested
looks good
