### ISSUE TITLE
Change wording of verification screens at first login

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#350]
# Why

For a user that is using a system set on "verification at first login" it's hard to understand, why he sees a OTP/MagicLink screen after entering the passcode. 
For this reason we want to change the wordings of the OTP/Magic Links screens if the user is asked to verify the email address. 

Texts and drafts can be found in this [Figma](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=10347%3A4781&mode=design&t=f4Tm1KVdd11F5jPB-1)

# TODOS

Following changes **only** apply if the identifier verification setting is set to "at first login" and the user sees one of the verification screens because he needs to verify the identifier and is not choosing/redirected to a fallback. 
=> only if a user is shown a verification screen after successfully verifying his passkey. 

- [x] If the condition above is met, show the user the according verification screen with the changed wordings as shown in the Figma. 
- [x] Make sure that all the text fields width are the same as the CTA button and the other components and that the text is continuing in a new line. 

# Acceptance criteria

- [x] User is in login flow, verifies passkey correctly and needs to verify identifier => sees alternative version of verification screen (OTP/Magic link)
- [x] Applies for EmailOtp
- [x] Applies for EmailLinkSent
- [x] Applies for PhoneOtp

**Comment by Adam3371** [comment]
Tested looks fine
