### ISSUE TITLE
Add a PasskeyAppendAfterHybrid Screen

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#351]
# Why
This is a followup ticket for [this ticket](https://github.com/corbado/corbado/issues/3293)

If a user logs in with the CDA (cross device authentication), we want to propose the user to append a passkey on the current device. 

A Figma draft for it can be found [here](https://www.figma.com/file/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?type=design&node-id=10353%3A5194&mode=design&t=f4Tm1KVdd11F5jPB-1)

# TODOS

- [ ] In the passkey-append-after-hybrid block, add a new PasskeyAppendAfterHybrid screen according to the Figma draft. 
- [ ] Add a "Don't show this again" checkbox. If the user ticks the checkbox and continues, the state is saved in the local storage of the browser (like the client side state information) => @incorbador please add informations here.
- [ ] If in the local storage a entry is found, that the user already have checkt the "Don't show me this again", scrip the screen and proceed with the next screen/login.
- [ ] Make sure that text and icon is not exceeding the width of the CTA. 

# Acceptance criteria

Here you must define the acceptance criteria of this issue (what has to work, what should the developer test and so on). Use TODO checkboxes (markdown).

- [ ] Screen is looking good for screens above and below 400px (like all the other screens)
- [ ] Screen supports light and dark mode.

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
