### ISSUE TITLE
Platform-specific versions of passkey-append screen. 

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#356]
# Why

This is a follow up ticket for [this ticket](https://github.com/corbado/corbado/issues/3304)

We want to show the user a platform-specific passkey-append screen with modified icons and wordings. Drafts and wordings can be found in this [Figma](https://www.figma.com/design/t68RCXKUvpdg7ljj2X0zGb/%5BOG%5D-Corbado-Developer-Panel?node-id=10418%3A3872&t=KBBPDK9ca0cI61pN-1)

# TODOS

Perform following tasks for both versions of the passkey-append screen (with and without identifier) for Signup and Login.  Information about the platform should be provided over the FAPI for this screens. 

- [x] Add 3 more version for the passkey-append screen according to the Figma drafts and adjust icons and wordings. The screens are for following platforms:
- [x] Apple
- [x] Android
- [x] Windows
- 
- [ ] Use the information from the FAPI to decide what screen is displayed to the user. 
- [x] If no or wrong information is shown, show the fallback screen (the passkey-append screen that we currently use)
- [x] Make sure that the icons and the texts are aligned correctly and the screen supports dark-mode and "shrinking".

# Acceptance criteria

Here you must define the acceptance criteria of this issue (what has to work, what should the developer test and so on). Use TODO checkboxes (markdown).

- [ ] On iOS or MacOS the Apple screen is shown 
- [x] On any Android device the Android screen is shown
- [x] On Windows 10 and 11 the Windows screen is shown
- [x] Fallback screen is the current passkey-append screen. 

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
