### ISSUE TITLE
Component change for DX improvement.

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#368]
# Why

After on of our developer implemented the UI components on a custom site, we got some feedback on how to improve the DX for the integration of the components.

The feedback from [this ticket](https://github.com/corbado/javascript/issues/363#issuecomment-2114622342):
- Our default component is very opinionated in styling, so we should enforce these opinions no matter what the sorrounding page context contains regarding styles. An example of this is text alignment. Our component should keep a text alignment of left even though the surrounding context might have a different text alignment. The user should only change this behaviour by customizing component classes directly, not the surrounding context.
- The component currently overflows on screen sizes / containers smaller than 400px as this value is hardcoded. Many phones have < 400px of screen size, so our default behaviour should constrain to these limits.
- We set hard limits for example for the .cb-pk-append-points-section and .cb-last-identifier classes of 83% width. When the component shrinks to adapt to smaller screen sizes, we loose too much available space by 'wasting' these 17% of potential space and this doesn't include the padding the components container has.

# TODOS

Here are the TODOS that result from the feedback.

- [ ] Ensure the component retains its default styles (e.g., left text alignment) regardless of surrounding page context.
- [ ] Allow users to customize these styles only by modifying component-specific classes.
- [ ] Remove the hardcoded 400px width limit and ensure the component adapts to screen sizes until 300px.
- [ ] Adjust the hardcoded 83% width for .cb-pk-append-points-section and .cb-last-identifier classes to utilize more available space.

# Acceptance criteria

- [ ] Styling is not overwrited by context of the hosting page. 
- [ ] Styling can be customisable in the component classes. 
- [ ] Component adapts to screen-sizes until 300 px

# Implementation idea

**Comment by Adam3371** [comment]
@incorbador => do you want to have a look at this ticket and evaluate/prioritise the TODOs? Once you approve it, we can start working on this.

**Comment by incorbador** [comment]
Good points, a few questions:
- what do we use instead of the 83% width? Should we go for a width:100% + a little bit of margin/padding on left and right side?
- "Ensure the component retains its default styles" => we had a similar problem when we worked on #334, the solution here is to explicitly specify those attributes (e.g. text-align: left) => what are the attributes we need to fix here exactly @Adam3371 or @Aby-JS

**Comment by Adam3371** [comment]
@incorbador
[This](https://github.com/corbado/javascript/issues/363#issuecomment-2114622342) where the issues we faced.
Point 1: Idk the exact solution for that but with smaller screens the icons shrink a lot. Could also think about removing the icon at a certain size. 
Point 2: the comment results from the implementation of the new components in the passkey.eu hosting page. See the issues we faced in the link.
Maybe @Aby-JS  have more insights/comments on your question
