### ISSUE TITLE
Component Improvements: CTA, Zoom-In, Button-alignment

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#370]
# Why

There are still minor bugs/improvements that can be made in the UI components with lower priority.

# TODOS

- [ ] On mobile (especially iOS) the CTA button in the pages are often in hover color. (Reproduce: Login init -> passkey append -back-navigation -> Login-init) (Screenshot 1)
- [ ] Other than the react playground, web-js and web-js-script playground still have a auto-zoom feature when clicking on a input field on a iPhone. Information can be found [here](https://stackoverflow.com/questions/4937345/javascript-web-app-control-iphone-zooming-on-input-focus-and-blur). (Note, react have also included some `<meta name="viewport" ... `
- [ ] The "combined width" of the 3-pack of social account buttons should match the width of the CTA, "or" separation line ect..(Screenshot 2)

# Screenshots
screenshot 1
![image](https://github.com/corbado/javascript/assets/56920624/80bc6c3a-f3f9-4958-aa80-d9eda8a603f5)

screenshot 2
<img width="353" alt="image" src="https://github.com/corbado/javascript/assets/56920624/4a13d821-be76-4a6f-9fe6-4c35d57b5c4b">
