### ISSUE TITLE
Improve passkey-button logic

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#371]
# Why

**The Passkey-Button (Client side state) is awesome!**

Still minor changes can be made to improve the AX and avoid user confusion. 

# TODOS

Ensure that with the identifier used in the Client side state it is always possible to log in. 

Currently it is not possible to use the identififier saved in client side state if:

- Identifier is changed during the signup process
- Email and Phone are activated but only phone is verified. (Client side state saves email)

- [ ] If a identifier is edited during the signup process, save the updated identifier in the client side state
- [ ] Always save the primary identifier of a user in the client side state.

# Acceptance criteria

- [ ] Changing identifier during signup saves the updated identifier.
- [ ] Signup with following settings makes it possible to use the passkey button
Verification:
- Email: at first login
- Phone: at signup
