### ISSUE TITLE
Change JavaScript Alert Text and Buttons

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#376]
# Why

In the signup process when navigating back, we show the user a JavaScript dialog in the browser that asks the user if he wants to continue the signup. Here the CTA ("OK"-button) should lead to a signup abort and the cancel should return to the signup process. (At this time it's the other way around)

# TODOS

- [ ] If a signup is aborted by the user's back navigation, show following text and if possible, also display it in 2 lines.
Are you sure you want to abort the signup process? 
Any information you’ve entered will be lost. 
- [ ] Swap the actions of the buttons: "Ok" should abort the signup process and "Cancel" should return to the signup flow.
- [ ] If possible, change the text of the "Ok" button to "Abort".

# Acceptance criteria

- [ ] Continues to work on all devices.
