### ISSUE TITLE
(Low Prio) Phone Input improvement

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#379]
# Why

In order to provide a user with a even better UX when authenticating with phone number, here are some improvements that can be made. 

# TODOS

- [ ] Make it possible to select country code by using Tab, Arrows and Enter Keys. 
- [ ] Don't allow any other characters than "+", and digits
- [ ] Keep search bar on top when scrolling 
- [ ] USA, Germany, India, GB on Top (KP: not sure about that probably skip)
- [ ] Once BE ready, pre-select the country code of the user 

# Acceptance criteria

- [ ] It is possible to select a country code without using the mouse
- [ ] Only digits and "+" are accepted in the input field
- [ ] When scrolling, search bar stays on top
