### ISSUE TITLE
Solve Keyboard Password Bar Flickering for iOS 17.x

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#380]
# Why

On iOS 17.x (16.x was not noted) the password bar of the keyboard is flickering when typing on the keyboard for entering any input field on the signup/login init screen and on login identifier edit  of our components. The problem arises especially if user is typing really fast on the keyboard. 
(See Video) 

The issue is visible on our **React** and **web-js** components.

# TODOS

- [ ] Research about the issue and find a solution that solves the problem. (See [Link1](https://github.com/flutter/flutter/issues/134723) and [Link2](https://github.com/facebook/react-native/issues/39411#issuecomment-2143680500), maybe it's helpful)
- [ ] If a solution is found, sync with @incorbador or @corbadoman  and implement the solution for all imput fields in signup, login and identifierEdtit screen.
- [ ] Make sure that all the functionallity is still working. 

# Acceptance criteria

- [ ] No flickering on iOS 17.x and still no flickering for previous versions.
- [ ] No flickering on any input field. 
- [ ] No flickering for react and web-js
- [ ] No flickering on different browsers

# Screen Recording
https://github.com/corbado/javascript/assets/56920624/fd235891-beef-49e9-b157-e61493d72439
