### ISSUE TITLE
Web-Js-Script Icon Coloring is not working.

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#384]
# Why

For our web-js-script package the icon coloring is not working resulting in not visible icons in our compontent. Colors seem to be set or to white or to black resulting in different icons missing in light and dark themes. 

Issue can be seen observed in this [demo page](https://web-js-script.demo.corbado.io/#signup-init)

# TODOS

- [ ] Find out how to support icon coloring for web-js-script and adjust the component in a way, that the screen looks identical as in React and Web-Js. 
- [ ] Component must support dark and light theme as in the React and Web-Js component.
- [ ] Check that Icon Coloring is supported in **every screen** in dark and in light mode and screens are identical als React and Web-Js. 
- [ ] Release the new version for web-js-script
- [ ] Remove the Note in the [Documentation](https://docs.corbado.com/frontend-integration/vanilla-js) that says that JS components added via CDN are not supporting Icon coloring.
- [ ] Bump the version of web-js-script for the [Web-js-script] Demo Application](https://web-js-script.demo.corbado.io/#signup-init)

# Acceptance criteria

- [ ] There should be no difference between Web-Js or Web-js-script.

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
