### ISSUE TITLE
Add User Management Panel/Identifier List to the UI Components.

### ISSUE THREAD

**Issue by Adam3371** [corbado/javascript#394]
# Why

This is a follow-up ticket for the "[Add API endpoints for user management panel (identifier verification)](https://github.com/corbado/corbado/issues/3414)" ticket.

We developed on Figma a **User Management Panel/Identifier List Component**. This panel should allow to add, delete and edit user's identifier and information. 

BEFORE YOU START:
- Name can only be added or edited, but not deleted.
- Username can only be added or edited, but not deleted.
- Email and Phone can only be added, deleted, verified or set as primary, but not edited. 
- Socials can only be deleted but not added or edited. 
- User management panel only shows activated identifer. (e.g. if phone is not activated, don't show that phone section)

Check out the [NOTION](https://www.notion.so/Identifier-list-component-e229302a19364601a010fedac4d13ecd?pvs=4) and the [FIGMA](https://www.figma.com/design/m80pv9mpeiQwJzObP0FswM/UI-Components?node-id=124-13307&t=Z3lbrzzvIJfYdfKh-1) pages. 

# TODOs

- [ ] Implement the User Management Panel for Mobile according to [this Figma draft](https://www.figma.com/design/m80pv9mpeiQwJzObP0FswM/UI-Components?node-id=3-14367&t=Z3lbrzzvIJfYdfKh-1). 
- [ ] Implement the User Management Panel for Desktop according to [this Figma draft](https://www.figma.com/design/m80pv9mpeiQwJzObP0FswM/UI-Components?node-id=3-14842&t=Z3lbrzzvIJfYdfKh-1). For themes, colors or any other uncertanty, refere to the mobile version, that is far more elaborated. 
- [ ] (If desired by stakeholders) Add mobile responsiveness for screens between Desktop and Mobile according to [this figma draft](https://www.figma.com/design/m80pv9mpeiQwJzObP0FswM/UI-Components?node-id=97-8753&t=Z3lbrzzvIJfYdfKh-1).
- [ ] Note that the identifier list component should look as similar as possible to the passkey list component

For additional uncertainties try to come up yourself with a solution or ask  @incorbador  

# Acceptance criteria

- [ ] User management panel looks like in the [Figma drafts](https://www.figma.com/design/m80pv9mpeiQwJzObP0FswM/UI-Components?node-id=124-13307&t=Z3lbrzzvIJfYdfKh-1), can be used as in the [Figma prototypes](https://www.figma.com/proto/m80pv9mpeiQwJzObP0FswM/UI-Components?page-id=3%3A4551&node-id=3-14368&viewport=12442%2C-4851%2C0.63&t=Pg7m6E49xEg52Ctj-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3%3A14368&show-proto-sidebar=1) and contains all the functionalities of the [Notion](https://www.notion.so/Identifier-list-component-e229302a19364601a010fedac4d13ecd?pvs=4) file. 

# Implementation idea

Here you can write down an implementation idea how you would implement this issue (where do put this feature like in what domain, what service, what layer, naming/key of the feature in the code).
