### ISSUE TITLE
Improve Vanilla JS for MPA

### ISSUE THREAD

**Issue by corbadoman** [corbado/javascript#472]
# TODOS

- [ ] Provide some sessionRefresh() method which must be called on each page
   - [ ] Where should we place it inside a HTML page?
- [ ] Implement or explain how you would handle Corbado.load() so you do not have to repeat it on each page (put it to some corbado.js file and load it on each page? will we have race conditions about "load order"?)
- [ ] Where should I put the script tag? head is the best because this way we are save everything is load?
