### ISSUE TITLE
Setup deployment to vercel

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#56]
### Why
We currently have two examples that demonstrate the usage of our SDKs. Currently one has to check out the code and manually start these examples on his machine. In this task we want to setup automatic deployment of those examples to Vercel.

### TODO
- [x] setup deployment for react-sdk-example
- [x] setup deployment for react-example
- [x] setup GitHub action to automate this flow

### Acceptance criteria
- [x] both examples can be tested on Vercel
- [x] examples are automatically updated when we push on main

### Implementation idea
- setup one Vercel project per example
- keep the build step inside the GitHub action and only use Vercel for deployment (as an alternative Vercel could also manage the building but afaik Vercel can not handle such multi-project repos out of the box)
- share one single Corbado project between all examples that are deployed to Vercel (for local development we use a separate projectID to not break the Vercel deployment when we change project configurations) => the rpID could be corbado.vercel.app (we might later set up custom domains at vercel)
