### ISSUE TITLE
Web-Core & React-SDK: Session Management

### ISSUE THREAD

**Issue by Aby-JS** [corbado/javascript#6]
### Why
To ensure user data integrity and security, Corbado aims to establish a robust session management system. This system will handle session data storage, retrieval, maintenance, and termination effectively across both the Web-Core and React-SDK.

### TODO
- [ ] Securely storing shortSession and longSession after logout and login
- [ ] Establish session termination logic in Web-Core (logout)
- [ ] Make shortSession available for clients (longSession should only be available internally for refresh)

### Acceptance criteria
- Register/login user => valid short term session should be available, refresh token should be stored
- Reload page => short term session and refresh token should still be available
- Logout user => localstorage should be cleared of user data (check using browser tools)
- All of these three points can be tested in playground/react-custom-ui

### Implementation idea
- Store shortSession in localstorage
- Store longSession as a HttpOnly cookie (like we do it today), for DEV projects also store it in localstorage (like we do it today)
- Web-core should offer these new calls: getShortSession, logout, getUser (this returns data based on getShortSession)
- Define a user interface (this is returned by getUser)
