### ISSUE TITLE
Manage error handling in react package

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#66]
### Why
Our web-core package's functionality produces two types of errors: RecoverableErrors and NonRecoverable errors. These error should now be handled in @corbado/react.

### TODO
- [ ] all RecoverableErrors should be handled in such a way that the user can continue his flow (e.g. by retrying his previous action or by using an email OTP fallback) => this means we need to show an error message, redirect to an error screen or call a fallback functionality (all of this should be described in our Figma)
- [ ] all NonRecoverableErrors should redirect the user to a NonRecoverableErrorScreen. This screen is shown in our Figma. The level of detail shown in this screen depends on the fact if the project is in DEV or in PROD mode
![Image](https://github.com/corbado/javascript/assets/134682658/11885079-8caa-419e-9065-471799e3b711)

### Acceptance criteria
- [ ] a comment in this ticket describes the tested RecoverableErrors and NonRecoverableErrors
- [ ] testing works locally and on Vercel

### Implementation idea
- [ ] build a new NonRecoverableErrorsScreen
- [ ] use "globalError" from @corbado/react-sdk to detect that a NonRecoverableError has occurred
