### ISSUE TITLE
Introduce test automation with Playwright

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#67]
### Why
As we are completing our initial version of react-sdk and react we want to add automated testing for the react package. We want to do that now because it tells us, if our code so far is testable. Additionally we then know if we break some of the existing capabilities of react-sdk and react when we change things in the frontend or in the backend.

### TODO
- [x] make a small concept what we need to mock for these tests
- [x] evaluate what we need to build to support these tests (do we need a separate test example application or can we use/adapt our current react-example)
- [x] add tests for signUp flow (we build tests for login, translations and UI customizations in a follow up ticket)
- [x] include these tests in a GitHub actions
- [x] Tests must be useable for React and other frameworks like Vue.js and Angular as well (we need to check how we "select" elements like "click button x"), so tests are not only used to test if react is bugfree but if Vue.js "has the same UI implementation" as well
- [ ] Tests run against self started instance of the project

### Acceptance criteria
- [x] one test for sign up that shows that passkey creation works
- [x] tests is green for the current state of the react package

### Implementation idea
What do we need to mock:
- Authenticators: There is the concept of [virtual authenticators](https://chromedevtools.github.io/devtools-protocol/tot/WebAuthn/) => these can be used to test webAuthn flows
- Corbado Relying Party Server: Here we can just use a dedicated Corabdo project (we can create a new one here where Abdullah and Martin both have access to) the only interesting thing here is email OTP => for the beginning we can make use of special test users that are supported by our Corbado backend (e.g. we can create a test user called internal-testing@corbado.com with a fixed OTP code like 123123) => ask @corbadovych for a project ID, he basically manages the "test projects"
