### ISSUE TITLE
Product management feedback: bugfixes & small improvements 

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#71]
### Why
This ticket includes first feedback from product management (Vincent). All points are meant to be quickly fixable => if one of them is more compicated it should become an extra ticket.

### TODO
**UI:**
- [x] change the cursor to 'pointer' for all buttons
- [x] change the font-weight of the primary button to bold
- [x] add loading animation to all buttons that trigger a longer running operation (e.g. a backend call or a passkey authentication)
- [x] change "Email Address is already in uses" to "Email address is already in use" (InitiateSignUp)
- [x] remove additional dot after "... screen lock code" (PasskeyBenefits)
- [x] center the logos + email providers (EmailOTP)
![image](https://github.com/corbado/javascript/assets/134682658/cac5488e-0370-43db-a829-b89d8a57fc20)
- [x] add auto-submit when the user has entered the last digit of the 6-digit code (EmailOTP)
- [x] please format email address fields as email (so that email styled keyboards are shown on mobile devices)
- [x] show a numbers-first keyboard => important for mobile devices (EmailOTP)
- [x] add autofill for name and email field (InitiateSignUp, InitiateLogin)

**Bugfixes to flow:**
- [x] If clicking on maybe later, I'm returned to the sign up screen but the account is already created and I get the "Email Address is already in use" error message (PasskeyBenefits)
- [x] Failing "Try Again" (e.g. by cancelling the passkey flow) redirects to the "You are not logged in screen" => we should stay on login/PasskeyError screen as long there is an error and as long as the user does leave that screen explicitly by clicking "Back" or "Email OTP" (login/PasskeyError)

### Backup
- [x] Link to PasskeyBenefits screen when clicking on "Passkeys" in "Log in even faster with Passkeys" (
