### ISSUE TITLE
Product management feedback: Conditional UI

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#72]
### Why
We got feedback regarding the implementation of conditional UI. This affects how we include the passkey login with the login's input form. 

### TODO
- [x] Make sure that conditional UI is only shown when there is a passkey
![image](https://github.com/corbado/javascript/assets/134682658/14974292-46ed-49d6-a8b7-5cd039ac5eef)
- [x] Show the conditional UI dropdown instead of the modal that we currently show
<img width="912" alt="image" src="https://github.com/corbado/javascript/assets/134682658/45da0418-86a0-4c27-ab59-b7764a43c983">

### Acceptance criteria
- [x] conditional UI autocomplete only pops up when a passkey has been setup and is availabel
- [x] conditional UI login is still possible (locally and on Vercel deployment on both example applications)

### Implementation idea
- [x] take a look at webauthn.io and the current webcomponent for reference
