### ISSUE TITLE
Update Vercel deployment to also incude branches with open PR

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#73]
### Why
Currently we sometimes have local build issues (e.g. missing scripts in package.json). This slows down the review of PRs. If we could run a Vercel build & deployment for every branch that has an open PR we as developers get faster feedback if our changes break local builds and can fix them.

### TODO
- [x] Enable Vercel deployment for branches with open PR for @corbado/react (@corbado/react-sdk is nice to have in this case)

### Acceptance criteria
- [x] additionally to the main branch deployment, there should be a deployment available for this ticket's branch
- [x] the build should break when there is a build issue (simulate this in this branch) => this issue should be visible in the PR

### Implementation idea
- [ ] ...
