### ISSUE TITLE
Open source this repository

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#76]
### Why
We want the frontend code to be open source. After we completed our first version of web-core, react-sdk and react we should open source this repository.

### TODO
- [ ] Rework the READMEs 
- [ ] Check the LICENSEs
- [ ] Check the /docs directory
- [ ] Make the repo public

### Implementation idea
