### ISSUE TITLE
Update documentation (READMEs)

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#77]
### Why
When we publish our packages we need READMEs for two main reasons:
- people who look at our packages on npmjs.com where the READMEs are shown
- people who check out our GitHub repo will look at the READMEs

### TODO
- [ ] Add a root README
- [ ] Add READMEs to packages/react, packages/react-sdk and packages/web-js (these are the ones that will be visible on npmjs.com)
- [ ] Go through the existing READMEs of packages/web-core, packages/shared-ui, packages/types and packages/e2e-tests and make sure that they do not contain left overs (e.g. TODOs) and that include some basic information about the package (these packages are not as important as the others though)

### Acceptance criteria
- [ ] READMEs look good on GitHub and on npmjs
- [ ] READMEs of packages/react, packages/react-sdk and packages/web-js have similar structure

#### Root README
- Include top image from README https://github.com/corbado/corbado-php/tree/16-improve-sdk ("we help you offer passkeys...)
- main Headline: Corbado JavaScript SDKs
- Include a few badges (license, documentation & slack)
- Sub line: Corbado's JavaScript SDKs allow you to integrate passkey based authentication into you webapps. These SDKs give you access to Corbado's bare functionalities and to its UI Components.
- Section 1: Get Started with Corbado: 1. Create an account, 2. Go through Corbado's setup wizard to configure you Corbado project and set up your project
- Section 2: Package overview: This repository contains all of Corbado's frontend JS packages. (now I would add a table that looks like this)
| Package name | Description | Link to example |
| react | Gives you access to prebuilt customizable UI components for you React project. When you build a React frontend, we recommend this package. | link |
| react-sdk | Gives you access to Corbado's functionality (without the UI components). Should be used when you have a React project but you want to build all authentication related components yourself | link |
- Section 3: Further documentation
- Section 4: License

#### Package README
- Include top image from README https://github.com/corbado/corbado-php/tree/16-improve-sdk ("we help you offer passkeys...)
- main Headline: <name of package> (e.g. @corbado/react)
- Include a few badges (license, documentation, slack, maybe also current version if this is not too hard)
- Short description about the package
- Section 1: Getting started (installation, example how to set up the package)
- Section 2: Usage (example how to access auth state like isAuthenticated and user, maybe also how to log out)
- Section 3: Support
- Section 4: License
