### ISSUE TITLE
Additional components: PasskeyList

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#78]
### Why
Currently, @corbado/react contains a CorbadoAuth components that handles user signUp and user login. For users that are logged in we also want to show a list of existing passkeys and allow them to manage them.

### TODO
- [ ] Create a new component called PasskeyList in @corbado/react. Is should list a user's passkeys, allow him to delete them and to create a new passkey on the current device

### Acceptance criteria
- [ ] passkeys can be listed, deleted and created
- [ ] the style and translations of the component can be changed similarly to CorabdoAuth
- [ ] the new component is included in our react-example

### Implementation idea
- take a look at the existing PasskeyList component
- the Figma designs include "Seen from this browser" and "Synced" chips => currently we do not get this data from backend so adding these tags is out of scope of this ticket
