### ISSUE TITLE
Add support for vanilla JS

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#79]
### Why
Additionally to @corbado/react that supports only react we want to add a package that supports users that want to include Corbado in their vanilla JS projects. Similarly with react, this should be possible for two different use cases: 
- developer only want to interact with our API and not use any of our UI components (@corbado/react-sdk)
- developer wants to use our API and our UI components (like @corbado/react)

### TODO
- [ ] Create one or two new packages (we need to decide for a name) 
- [ ] Evaluate if we can reuse @corbado/react to create the UI components for vanilla JS
- [ ] Add a new example application
- [ ] Complete and test the package(s)

### Acceptance criteria
- [ ] UI components are configurable similar to @corabdo/react (translations and styles)
- [ ] UI components work in our new example

### Implementation idea
- Do we create two new packages (one of sdk only and another one for UI) or only a single new one?
- Can we use these new components on other non-react frameworks like Vue, Angular or Nuxt as long as we don't have dedicated support for these?
