### ISSUE TITLE
Web-Core & React-SDK: Session Error Handling

### ISSUE THREAD

**Issue by Aby-JS** [corbado/javascript#8]
### Why
Currently our methods in web-core are no throwing any typed errors. We now want to give ourselves more control about how to handle errors in react. Thus these methods in web-core now should return errors.

### TODO
- [x] define errors in web-core and return them from AuthService's methods
- [x] demonstrate how to process these errors in react-sdk-example

### Acceptance criteria
- [x] react-sdk-example processes errors (show generic error page, show error messages to the user, call fallback methods)

### Implementation idea
- define errors centrally in web-core
- there will be multiple sources for errors (api calls, wrong configuration, platform authenticator calls) => handle all of them and transform them to our custom error types
- proposal: use custom error types over plain JS errors => they can be part of the method signature and it's a bit more clear what errors can occurr when calling a web-core methods
