### ISSUE TITLE
Add support for Next JS

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#80]
### Why
Additionally to @corbado/react that supports only react we want to add a package that supports users that want to include Corbado in their Next JS project. We might break this issue down into smaller tasks as we start working on it.

### TODO
- [ ] Create a new package: @corbado/next-js
- [ ] Check other Next JS packages (e.g. Clerks) to get a good understanding of the challenges
- [ ] Add a new example application (next-js-example)
- [ ] Complete and test the package(s)

### Acceptance criteria
- [ ] UI components are configurable similar to @corabdo/react (translations and styles)
- [ ] UI components work in our new example

### Implementation idea
- tbd. (especially how much we want to optimize for server components here)
- things that should be included: middleware

**Comment by incorbador** [comment]
For now have just built an example on how to use the react package inside a Next application.
