### ISSUE TITLE
Product management feedback 2

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#92]
# Why

This ticket includes subsequent feedback from product management (Vincent, Stefan). All points are meant to be quickly fixable => if one of them is more complicated it should become an extra ticket.

# TODOS
- [x] name and email fields are overlapping with their labels (SignUp) => we should either increase the distance between them or change something about the label animation
![image](https://github.com/corbado/javascript/assets/134682658/c7c641f0-9f8a-4d17-b470-0db65a68fb6a)
- [ ] empty submits don't show an error message (SignUp, Login, EmailOTP) => we should show an error here
- [x] if there is an error the placeholders are not centered anymore (SignUp)
![image](https://github.com/corbado/javascript/assets/134682658/42a84552-3a08-4f6e-b505-1c2f3816fd45)
- [x] the height of the card in loading state should be similar to the card in SignUp or Login state so that there is no flickering 
- [x] remove unused translations (e.g. signup.start.validationError_name, validationError_email, validationError_emailExists, ...)
- [x] include email address in EmailOTP screens
![image](https://github.com/corbado/javascript/assets/134682658/e1ebb68b-133f-4d19-afde-5859c58058b7)

Removed:
- refactor translations by making use of interpolation => we should no longer concatenate strings in React (e.g. "We'll create an account for")
