### ISSUE TITLE
Follow up: PasskeyList

### ISSUE THREAD

**Issue by incorbador** [corbado/javascript#93]
# Why

We created a basic PasskeyList component. We now want to fix a few outstanding things as part of this ticket.

# TODOS

- [ ] Handle errors during deletePasskey and appendPasskey (especially the error that appears when a user tries to create a second passkey on the current device)
- [ ] Animate the "Create passkey" button while a passkey is created
- [ ] Run the deletion of a passkey inside the dialog and animate the delete button during the deletion
- [ ] Make PasskeyList responsive => it should also work on Mobile devices
- [ ] Improve button styling (add horizontal paddings)

# Acceptance criteria

Here you must define the acceptance criteria of this issue (what has to work, what should the developer test and so on). Use TODO checkboxes (markdown).

- [ ] PasskeyList looks good on mobile devices as well

# Implementation idea
