### ISSUE TITLE
Harden error handling for wrong FrontendAPI/CNAME

### ISSUE THREAD

**Issue by corbadoman** [corbado/javascript#96]
# Why

To further optimize our developer experience we need to better validate for the FrontendAPI configuration. If the project is env=prod and uses Corbado session management we need to have a CNAME set and used as FrontendAPI. Otherwise the FrontendAPI can not set the long-term session cookie because its `SameSite=lax´.

# TODOS

- [ ] Check project config if env=prod and Corbado session management is used, if both are true there must be a FrontendAPI set
- [ ] Additionally we should validate that the FrontendAPI is not our default FrontendAPI host/URL (pro-123.frontendapi.corbado.io)

# Acceptance criteria

- [ ] Error is thrown/shown if I do not set a FrontendAPI if project is env=prod and uses Corbado session management

# Implementation idea

Right now the CNAME is stored in core database. So right now it is not part of the projectconfig (backendapi database). Need to solve this somehow (maybe easiest to just store it in backendapi database as well).
